version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.1.0
  node: circleci/node@5.0.0
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - aws-cli/setup
      - eb/setup
      - node/install: 
          node-version: 14.19.0
      - run:
          name: install all pakages dependency (npm i ) 
          command: npm run install 
      - run:
          name: build the backend then frontend 
          command: npm run build
      - run:
          name: Test the backend then frontend 
          command: npm run test
      - run:
          name: deploy backend (elastic beanstalk) the deploy frontend  (s3)
          command: npm run deploy
